Auth.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Auth.Application.Dtos;
using Auth.Application;
using Auth.Utility;
using Auth.Web.Models;
using SqlSugar;
using Auth.SqlSugar;
using System.Linq;
using Microsoft.AspNetCore.Http;

namespace Auth.Web.Controllers
{
    /// <summary>
    /// 功能管理控制器
    /// </summary>
    public class MenuController : AuthControllerBase
    {
        private readonly IMenuAppService _menuAppService;

        public MenuController(IMenuAppService menuAppService)
        {
            _menuAppService = menuAppService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult EditPage(string id, string pid)
        {

            bool isAdd = string.IsNullOrEmpty(id);
            id = string.IsNullOrEmpty(id) ? pid : id;
            ViewData["id"] = id;
            ViewData["isAdd"] = isAdd;
            return View();
        }
        /// <summary>
        /// 获取菜单JSON数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetMenu()
        {
            var userId = HttpContext.Session.GetString("CurrentUserId");
            var menus = _menuAppService.GetMenusByUser(userId);
            return Json(menus);
        }

        /// <summary>
        /// 获取功能树JSON数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetMenuTreeData()
        {
            var menus = _menuAppService.GetAllList();
            List<TreeModel> treeModels = new List<TreeModel>();

            foreach (var menu in menus)
            {
                //区别菜单和按钮的图标
                var icon = menu.Type == 0 ? "" : "layui-icon layui-icon-fonts-strong";
                treeModels.Add(new TreeModel()
                {
                    Id = menu.Id,
                    Text = menu.Name,
                    Parent = menu.ParentId == Guid.Empty.ToString() ? "#" : menu.ParentId,
                    IconSkin = icon
                });
            }

            return Json(new ReturnModel() {Data = treeModels});
        }

        /// <summary>
        /// 获取表格头
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetMenuTableCols()
        {
            List<LayuiColsModel> colsList = new List<LayuiColsModel>();
            colsList = GetTableCols<MenuDto>();
            return Json(new ReturnModel() {Data = colsList});
        }

        /// <summary>
        /// 获取子级功能列表
        /// </summary>
        /// <returns></returns>
        public IActionResult GetMneusByParent(string parentId, int page, int limit, string searchParam, string field, string order)
        {
            var orderField = string.Empty;
            if (!string.IsNullOrEmpty(field))
                orderField = field + " " + order;
            List<IConditionalModel> conModels = ConditionHelper.GetCondition(searchParam);
            conModels.Add(new ConditionalModel()
            {
                FieldName = "parentId",
                ConditionalType = ConditionalType.LikeLeft,
                FieldValue = parentId
            });
            var result = _menuAppService.GetTableList(page, limit, conModels, orderField);
            return Ok(result);
        }

        /// <summary>
        /// 新增或编辑功能
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Edit(MenuDto dto)
        {
            var result = new ReturnModel();
            if (!ModelState.IsValid)
            {
                result.Msg = GetModelStateError();
                return Json(result);
            }

            if (_menuAppService.InsertOrUpdate(dto))
            {
                result.Success = true;
                return Json(result);
            }

            return Json(result);
        }

        [HttpPost]
        public IActionResult DeleteMuti(string ids)
        {
            ReturnModel res = new ReturnModel();
            try
            {
                string[] idArray = ids.Split(',');
                var delIds = idArray.Where(s => !string.IsNullOrEmpty(s)).ToList();
                _menuAppService.Delete(delIds);
                res.Msg = "删除成功";
                res.Success = true;
                return Json(res);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Get(string id, bool isAdd)
        {
            var menu = new MenuDto();
            if (!isAdd)
            {
                menu = _menuAppService.QuerySingle(id);
            }
            else
            {
                menu.ParentId = id;
                menu.No = _menuAppService.GetNextNo(id);
            }

            return Json(new ReturnModel() {Data = menu});
        }
    }

}

Auth.Web/Views/Menu/EditPage.cshtml
@*菜单按钮编辑页面*@

@{
    Layout = "_Layout";
    string id  =(string)ViewData["id"];
    
    bool isAdd = (bool)ViewData["isAdd"];
}
<div style="margin: 15px;">
    <form class="layui-form" id="updateForm" action="@Url.Action("Edit","Menu")">
        <div class="layui-form-item">
            <label class="layui-form-label">编号</label>
            <div class="layui-input-block">
                <input type="text" disabled name="No" class="layui-input" data-bind="value:no">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">类型</label>
            <div class="layui-input-block">
                <input type="radio" name="type" value="0" lay-filter="radio" data-bind="checkedValue: 0,checked: type" title="菜单">
                <input type="radio" name="type" value="1" lay-filter="radio" data-bind="checkedValue: 1,checked: type" title="头部按钮">
                <input type="radio" name="type" value="2" lay-filter="radio" data-bind="checkedValue: 2,checked: type" title="操作栏按钮">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">URL</label>
            <div class="layui-input-block">
                <input type="text" name="url" class="layui-input" data-bind="value:url" value="" placeholder="Admin/Index">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">名称</label>
            <div class="layui-input-block">
                <input type="text" name="name" lay-verify="required" data-bind="value:name" placeholder="请输入菜单名称" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">编码</label>
            <div class="layui-input-block">
                <input type="text" name="code" lay-verify="required" data-bind="value:code" placeholder="请输入菜单编码" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">排序</label>
            <div class="layui-input-block">
                <input type="text" name="serialNumber" lay-verify="number" data-bind="value:serialNumber" placeholder="请输入排序编号" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">图标</label>
            <div class="layui-input-inline">
                <input type="text" disabled name="icon" lay-verify="required" data-bind="value:icon" placeholder="请选择图标" class="layui-input">
            </div>
            <div class="layui-form-mid layui-word-aux">
                <i class="layui-icon pick-icon">&#xe615;</i>
            </div>
        </div>
       
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="btnSubmit">提交</button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        function vModel() {
            this.id= ko.observable("");
            this.no = ko.observable("");
            this.name = ko.observable("");
            this.url = ko.observable("");
            this.code = ko.observable("");
            this.icon = ko.observable("");
            this.parentId = ko.observable(""),
            this.remarks = ko.observable("");
            this.serialNumber = ko.observable("");
            this.type = ko.observable("");
        }
        var model= new vModel();
        layui.use(['element', 'layer', 'form'], function () {
            var $ = layui.jquery,
                form = layui.form;
            form.on('radio(radio)', function(data) {
                model.type(data.value);
            }); 
            $.ajax({
                type: "Get",
                url: "/Menu/Get?id="+'@id'+"&isAdd=@isAdd", //获取数据的ajax请求地址
                success: function (res) {
                    if (res.success) {
                        ko.mapping.fromJS(res.data, {}, model);
                        form.render();
                    } else {
                        admin_error(res.msg);
                    }
                }
            });
            //监听提交
            form.on('submit(btnSubmit)', function (data) {
                $.ajax({
                    url: $("#updateForm").attr("action"),
                    type: 'post',
                    dataType: 'json',
                    async: false,
                    data: model,//$("#updateForm").serialize(),
                    success: function (res) {
                        if (res.success) {
                            admin_success();
                            parent.layer.closeAll('iframe');
                        } else {
                            admin_error(res.msg);
                        }
                    }
                });
                return false;
            });

            $('.pick-icon').on('click', function () {
                layer.open({
                    type: 2,
                    title: "选择图标",
                    shadeClose: true,
                    shade: 0.4,
                    area: ['90%', '90%'],
                    content: "@Url.Action("GetIcon","Home")",
                    btn: ['确定','关闭'],
                    yes: function(index){
                        //当点击‘确定’按钮的时候，获取弹出层返回的值
                        var res = window["layui-layer-iframe" + index].callbackdata();
                        model.icon(res.icon_code);
                        //最后关闭弹出层
                        layer.close(index);
                    },
                    cancel: function(){
                        //右上角关闭回调
                    }
                });
            });
        });
        ko.applyBindings(model);//注册vModel
    </script>
</div>

Auth.Web/Views/Menu/Index.cshtml
@{
    ViewBag.CurrentMenu = "Menu";
    Layout = "_Layout";
}
<div class="layui-row">
    <div class="layui-col-md3">
        <ul id="MenuTree" class="ztree"> </ul>
    </div>
    <div class="layui-col-md9">
        <div id="searchBar"></div>
        <table id="menuTable" class="layui-table" lay-filter="menuTable"></table>
    </div>
</div>
<script type="text/javascript">
    function vModel() {
        this.edit = ko.observable(false);
        this.del = ko.observable(false);
    }
    var model = new vModel();
    var selectedMenuId = "00000000-0000-0000-0000-000000000000";
    var cols ="";

    layui.use(['table', 'ztree', 'jquery', 'searchTable'],
        function () {
            var table = layui.table, ztree = layui.ztree, $ = layui.jquery, searchTable = layui.searchTable;
            //加载表头
            var loadCols = function () {
                $.ajax({
                    url: '@Url.Action("GetMenuTableCols", "Menu")',
                    type: 'post',
                    dataType: 'json',
                    success: function (res) {
                        if (res.success) {
                            cols = [res.data];
                        } else {
                            admin_error(res.msg);
                        }
                    }
                });
            };

            var initTree = function () {
                var zTreeObj;
                var setting = {
                    view: { selectedMulti: false },
                    data: {
                        key: {
                            name: 'text',
                            title: 'text'
                        },
                        simpleData: {
                            enable: true,
                            idKey: 'id',
                            pIdKey: 'parent'
                        }
                    },
                    callback: {
                        beforeClick: beforeClick
                    }

                };
                $.ajax({
                    type: "Get",
                    url: "/Menu/GetMenuTreeData?_t=" + new Date().getTime(), //获取数据的ajax请求地址
                    success: function (res) {
                        if (!res.success) {
                            admin_error(res.msg);
                        }
                        zTreeObj = $.fn.zTree.init($("#MenuTree"), setting, res.data);
                        zTreeObj.expandAll(true);
                        $("#MenuTree_1_span").click();
                    }
                });
            };
            function beforeClick(treeId, treeNode, clickFlag) {
                if (treeNode) {
                    selectedMenuId = treeNode.id;
                    loadTables();
                };
                return (treeNode.click != false);
            }

            //加载表格数据
            var loadTables = function () {
                var tableIns = table.render({
                    elem: '#menuTable',
                    id: 'menuTable',
                    url: "/Menu/GetMneusByParent?parentId=" + selectedMenuId + "&_t=" + new Date().getTime(),
                    page: true, //开启分页
                    loading: true,
                    toolbar: '#toolbarButton',
                    height: 'full-120',
                    autoSort: false,
                    cols: cols
                });
                searchTable.init(tableIns);
            };
            $(document).ready(function () {
                loadCols();
                initTree();
            });
            //监听排序
            table.on('sort(menuTable)', function (obj) {
                table.reload('menuTable', {
                    initSort: obj //记录初始排序，如果不设的话，将无法标记表头的排序状态。
                    , where: { //请求参数（注意：这里面的参数可任意定义，并非下面固定的格式）
                        field: obj.field //排序字段
                        , order: obj.type //排序方式
                    }
                });
            });

            //表头工具栏事件
            table.on('toolbar(menuTable)', function (obj) {
                var checkStatus = table.checkStatus(obj.config.id);
                var data = checkStatus.data;
                switch (obj.event) {
                    case 'loadTopMenu':
                        selectedMenuId = "00000000-0000-0000-0000-000000000000";
                        loadTables();
                        break;
                    case 'editMenu':
                        if (data.length != 1) {
                            top.layer.msg("请选择一行数据。", { icon: 0, offset: '15px' });
                            return false;
                        }
                        top.layer.open({
                            title: '编辑',
                            area: ["600px", "500px"],
                            type: 2,
                            maxmin: true,
                            content: '@Url.Action("EditPage", "Menu")?id=' + data[0].id,
                            end: function () {
                                table.reload("menuTable");
                                initTree();
                            }
                        });
                        break;
                    case 'addMenu':
                        top.layer.open({
                            title: '新增',
                            area: ["600px", "500px"],
                            type: 2,
                            maxmin: true,
                            content: '@Url.Action("EditPage", "Menu")?pid=' + selectedMenuId,
                            end: function () {
                                table.reload("menuTable");
                                initTree();
                            }
                        });
                        break;
                    case 'delMenu':
                        var ids = '';
                        for (var i = 0; i < data.length; i++) {
                            ids += data[i].id + ',';
                        }
                        if (ids.length < 1) {
                            top.layer.msg("请选择要删除的记录。", { icon: 0, offset: '15px' });
                            return;
                        }; //询问框
                        top.layer.confirm("您确认删除选定的记录吗？",
                            {
                                btn: ["确定", "取消"]
                            },
                            function () {
                                var sendData = { "ids": ids };
                                $.ajax({
                                    url: '@Url.Action("DeleteMuti", "Menu")',
                                    type: 'post',
                                    data: sendData,
                                    dataType: 'json',
                                    success: function (res) {
                                        if (res.success) {
                                            top.layer.msg(res.msg, { icon: 1, offset: '15px' });
                                            table.reload("menuTable");
                                            initTree();
                                        } else {
                                            top.layer.msg(res.msg, { icon: 2, offset: '15px' });
                                        }
                                    }
                                });
                            });
                        break;
                }
            });
        });
    ko.applyBindings(model);//注册vModel
</script>