Auth.Web/Components/NavigationViewComponent.cs
using Auth.Application;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Auth.Application.Dtos;

namespace Auth.Web.Components
{
    [ViewComponent(Name = "Navigation")]
    public class NavigationViewComponent : ViewComponent
    {
        private readonly IMenuAppService _menuAppService;
        private readonly IUserAppService _userAppService;
        public NavigationViewComponent(IMenuAppService menuAppService, IUserAppService userAppService)
        {
            _menuAppService = menuAppService;
            _userAppService = userAppService;
        }

        public IViewComponentResult Invoke()
        {
            var userId = HttpContext.Session.GetString("CurrentUserId");
            var  menus = _menuAppService.GetMenusByUser(userId);
            ViewData["MenuHtml"] = GetMenu(menus);
            return View();
        }
        /// <summary>
        /// 获取菜单
        /// </summary>
        /// <param name="menuDtos"></param>
        /// <returns></returns>
        private string GetMenu(List<MenuDto> menuDtos)
        {
            StringBuilder sb = new StringBuilder();
            var parentMenu = menuDtos.Where(s => s.No.Length < 4).ToList();
            foreach (var item in parentMenu)
            {
                var childMenu = menuDtos.Where(s => s.ParentId == item.Id).ToList();
                if (childMenu.Any())
                {
                    sb.Append(
                        $"<li ><a href = \"javascript:;\" ><i class=\"layui-icon\">{item.Icon}</i><cite>{item.Name}" +
                        $"</cite><i class=\"iconfont nav_right\">&#xe697;</i></a>");
                    GetChildMenu(menuDtos, item.Id,sb);
                    sb.Append("</li>");
                }
                else
                {
                    sb.Append($"<li><a _href = \"{item.Url}\" ><i class=\"layui-icon\">{item.Icon}</i><cite>{item.Name}" +
                              $"</cite></a> </li >");
                }
            }

            return sb.ToString();
        }
        /// <summary>
        /// 遍历子菜单
        /// </summary>
        /// <param name="menuDtos"></param>
        /// <param name="id"></param>
        /// <param name="sb"></param>
        public void GetChildMenu(List<MenuDto> menuDtos, string id, StringBuilder sb)
        {
            sb.Append("<ul class=\"sub-menu\">");
            var menuList = menuDtos.Where(s => s.ParentId == id);
            foreach (var item in menuList)
            {
                var childMenu = menuDtos.Where(s => s.ParentId == item.Id);
                if (childMenu.Any())
                {
                    sb.Append($"<li><a href = \"javascript:;\" ><i class=\"layui-icon\">{item.Icon}</i><cite>{item.Name}" +
                        $"</cite><i class=\"iconfont nav_right\">&#xe697;</i></a>");
                    GetChildMenu(menuDtos, item.Id, sb);
                    sb.Append("</li>");
                }
                else
                {
                    sb.Append($"<li><a _href = \"{item.Url}\" ><i class=\"layui-icon\">{item.Icon}</i><cite>{item.Name}" +
                              $"</cite></a> </li >");
                }
            }
            sb.Append("</ul>");
        }
    }
}

Auth.Web/Controllers/HomeController.cs
using Auth.Application;
using Auth.Application.Dtos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace Auth.Web.Controllers
{
    public class HomeController : AuthControllerBase
    {
        private readonly IHttpContextAccessor _httpContext;
        private readonly IUserAppService _userService;
        public HomeController(IHttpContextAccessor httpContext, IUserAppService userService)
        {
            _httpContext = httpContext;
            _userService = userService;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
           var userIs= _httpContext.HttpContext.Session.GetString("CurrentUserId");
            UserDto user =_userService.QuerySingle(userIs);
            ViewData["User"] = user;
            return View();
        }

        public IActionResult GetIcon()
        {
            ViewData["Title"] = "选择图标";
            return View();
        }
    }
}

Auth.Web/Views/Home/Index.cshtml
@using Auth.Application.Dtos
@{
    Layout = null;
    var user = ViewData["User"] as UserDto;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Auth后台管理</title>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8"/>
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link href="~/css/font.css" rel="stylesheet" />
    <link href="~/css/xadmin.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/lib/layui/layui.js"></script>
    <script src="~/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
        <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
        <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo"><a href="./index.html">X-admin v2.0</a></div>
        <div class="left_open">
            <i title="展开左侧栏" class="iconfont">&#xe699;</i>
        </div>
        <ul class="layui-nav left fast-add" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">+新增</a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd><a onclick="x_admin_show('资讯','http://www.baidu.com')"><i class="iconfont">&#xe6a2;</i>资讯</a></dd>
                    <dd><a onclick="x_admin_show('图片','http://www.baidu.com')"><i class="iconfont">&#xe6a8;</i>图片</a></dd>
                    <dd><a onclick="x_admin_show('用户','http://www.baidu.com')"><i class="iconfont">&#xe6b8;</i>用户</a></dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav right" lay-filter="">
            <li class="layui-nav-item">
                <a href="javascript:;">@user.Name</a>
                <dl class="layui-nav-child">
                    <!-- 二级菜单 -->
                    <dd><a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a></dd>
                    <dd><a onclick="x_admin_show('切换帐号','http://www.baidu.com')">切换帐号</a></dd>
                    <dd><a href="javascript:;">退出</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item to-index"><a href="#">前台首页</a></li>
        </ul>

    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
    <!-- 左侧菜单开始 -->
    <div class="left-nav">
        <div id="side-nav">
            <ul id="nav">
                @await Component.InvokeAsync("Navigation")
            </ul>
        </div>
    </div>
    <!-- <div class="x-slide_left"></div> -->
    <!-- 左侧菜单结束 -->
    <!-- 右侧主体开始 -->
    <div class="page-content">
        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
            <ul class="layui-tab-title">
                <li class="home"><i class="layui-icon">&#xe68e;</i>我的桌面</li>
            </ul>
            <div class="layui-tab-content">
                <div class="layui-tab-item layui-show">
                </div>
            </div>
        </div>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
    <!-- 底部开始 -->
    <div class="footer">
        <div class="copyright">Copyright ©2017 x-admin v2.3 All Rights Reserved</div>
    </div>
    <!-- 底部结束 -->
</body>
</html>