Auth.Web/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Auth.Application;
using Auth.Web.Models;
using Auth.Application.Dtos;
using SqlSugar;
using Auth.SqlSugar;

namespace Auth.Web.Controllers
{
    public class DepartmentController : AuthControllerBase
    {
        private readonly IDepartmentAppService _service;
        public DepartmentController( IDepartmentAppService service)
        {
            _service = service;
        }
        

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult EditPage(string id, string pid)
        {
            bool isAdd = string.IsNullOrEmpty(id);
            id = string.IsNullOrEmpty(id) ? pid : id;
            ViewData["id"] = id;
            ViewData["isAdd"] = isAdd;
            return View();
        }

        /// <summary>
        /// 获取表格头
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetDepartmentTableCols()
        {
            List<LayuiColsModel> colsList = new List<LayuiColsModel>();
            colsList = GetTableCols<DepartmentDto>();
            return Json(new ReturnModel() { Data = colsList });
        }

        /// <summary>
        /// 获取部门 树形表格json数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetDepartTreeTable(string searchParam, string field, string order)
        {
            var orderField = " No asc ";
            if (string.IsNullOrEmpty(field))
                orderField = field + " " + order;
            List<IConditionalModel> conModels = ConditionHelper.GetCondition(searchParam);
            conModels.Add(new ConditionalModel()
            {
                FieldName = "isDeleted",
                ConditionalType = ConditionalType.Equal,
                FieldValue = "0"
            });
            var result = _service.GetTableList(1, 100000, conModels, orderField);
            return Json(result);
        }


        /// <summary>
        /// 获取功能树JSON数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetTreeData()
        {
            var dtos = _service.GetAllList();
            List<TreeModel> treeModels = new List<TreeModel>();
            foreach (var dto in dtos)
            {
                treeModels.Add(new TreeModel() { Id = dto.Id, Text = dto.Name, Parent = dto.ParentId == Guid.Empty.ToString() ? "0" : dto.ParentId });
            }
            
            return Json(new ReturnModel{Data = treeModels});
        }

        /// <summary>
        /// 获取下拉树JSON数据
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetSelectData()
        {
            var dtos = _service.QueryAll(s=>s.No.Length==3);
            List<SelectTree> treeModels = new List<SelectTree>();
            foreach (var dto in dtos)
            {
                treeModels.Add(new SelectTree() { Value = dto.Id, Name = dto.Name,Children = GetChildren(dto.Id) });
            }

            return Json(treeModels);
        }

        /// <summary>
        /// 获取 下级部门
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public List<SelectTree> GetChildren(string id)
        {
            var result = _service.QueryAll(s => s.ParentId == id);
            List<SelectTree> treeModels = new List<SelectTree>();
            foreach (var item in result)
            {
                if (_service.QueryAll(s => s.ParentId == item.Id).Count>0)
                {
                    treeModels.Add(new SelectTree() { Value = item.Id, Name = item.Name,Children = GetChildren(item.Id) }); 
                }
                else
                {
                    treeModels.Add(new SelectTree() { Value = item.Id, Name = item.Name, Children = null});
                }
            }
            return treeModels;
        }

        /// <summary>
        /// 获取子级列表
        /// </summary>
        /// <returns></returns>
        public IActionResult GetChildrenByParent(string parentId, int page, int limit = 15)
        {
            List<IConditionalModel> conModels = new List<IConditionalModel>
            {
                new ConditionalModel()
                {
                    FieldName = "parentId",
                    ConditionalType = ConditionalType.Equal,
                    FieldValue = parentId
                }
            };
            var result = _service.GetTableList(page, limit, conModels);
            return Json(result);
        }

        /// <summary>
        /// 新增或编辑功能
        /// </summary>
        /// <param name="dto"></param>
        /// <returns></returns>
        public IActionResult Edit(DepartmentDto dto)
        {
            ReturnModel r = new ReturnModel
            {
                Success = false,
                Msg = "操作失败！"
            };
            if (!ModelState.IsValid)
            {
                return Json(r);
            }

            if (_service.InsertOrUpdate(dto))
            {
                return Json(new ReturnModel {Success = true, Msg = "操作成功！"});
            }

            return Json(r);
        }

        public IActionResult DeleteMuti(string ids)
        {
            ReturnModel r = new ReturnModel
            {
                Success = false,
                Msg = "操作失败！"
            };
            try
            {
                string[] idArray = ids.Split(',');
                List<string> delIds = new List<string>();
                foreach (string id in idArray)
                {
                    delIds.Add(id);
                }

                _service.Delete(delIds);
                return Json(new ReturnModel() {Success = true, Msg = "操作成功！"});
            }
            catch (Exception ex)
            {
                r.Msg = ex.Message;
                return Json(r);
            }
        }
        public IActionResult Delete(string id)
        {
            ReturnModel r = new ReturnModel
            {
                Success = false,
                Msg = "操作失败！"
            };
            _service.Delete(id);
            return Json(new ReturnModel() { Success = true, Msg = "操作成功！" });
        }
        public IActionResult Get(string id, bool isAdd)
        {
            var depart = new DepartmentDto();
            if (!isAdd)
            {
                depart = _service.QuerySingle(id);
            }
            else
            {
                depart.ParentId = id;
                depart.No = _service.GetNextNo(id);
            }

            return Json(new ReturnModel() { Data = depart });
        }
    }
}

Auth.Web/Views/Department/EditPage.cshtml
@*部门编辑页面*@

@{
    Layout = "_Layout";
    string id = (string)ViewData["id"];

    bool isAdd = (bool)ViewData["isAdd"];
}
<div style="margin: 15px;">
    <form class="layui-form" id="updateForm" action="@Url.Action("Edit","Department")">
        <div class="layui-form-item">
            <label class="layui-form-label">编号</label>
            <div class="layui-input-block">
                <input type="text" disabled name="No" class="layui-input" data-bind="value:no">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">编码</label>
            <div class="layui-input-block">
                <input type="text" name="code" lay-verify="required" data-bind="value:code" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">部门名称</label>
            <div class="layui-input-block">
                <input type="text" name="name" lay-verify="required" data-bind="value:name" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <textarea name="remarks" class="layui-textarea" data-bind="value:remarks"></textarea>
            </div>
        </div>

        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="btnSubmit">提交</button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        function vModel() {
            this.id= ko.observable("");
            this.no = ko.observable("");
            this.name = ko.observable("");
            this.code = ko.observable("");
            this.parentId = ko.observable(""),
            this.remarks = ko.observable("");
        }
        var model= new vModel();
        layui.use(['element', 'layer', 'form'], function () {
            var $ = layui.jquery,
                form = layui.form;
            
            $.ajax({
                type: "Get",
                url: "/Department/Get?id="+'@id'+"&isAdd=@isAdd", //获取数据的ajax请求地址
                success: function (res) {
                    if (res.success) {
                        ko.mapping.fromJS(res.data, {}, model);
                        form.render();
                    } else {
                        admin_error(res.msg);
                    }
                }
            });
            //监听提交
            form.on('submit(btnSubmit)', function (data) {
                $.ajax({
                    url: $("#updateForm").attr("action"),
                    type: 'post',
                    dataType: 'json',
                    async: false,
                    data: model,//$("#updateForm").serialize(),
                    success: function (res) {
                        if (res.success) {
                            admin_success();
                            parent.layer.closeAll('iframe');
                        } else {
                            admin_error(res.msg);
                        }
                    }
                });
                return false;
            });

            $('.pick-icon').on('click', function () {
                layer.open({
                    type: 2,
                    title: "选择图标",
                    shadeClose: true,
                    shade: 0.4,
                    area: ['90%', '90%'],
                    content: "@Url.Action("GetIcon","Home")",
                    btn: ['确定','关闭'],
                    yes: function(index){
                        //当点击‘确定’按钮的时候，获取弹出层返回的值
                        var res = window["layui-layer-iframe" + index].callbackdata();
                        model.icon(res.icon_code);
                        //最后关闭弹出层
                        layer.close(index);
                    },
                    cancel: function(){
                        //右上角关闭回调
                    }
                });
            });
        });
        ko.applyBindings(model);//注册vModel
    </script>
</div>

Auth.Web/Views/Department/Index.cshtml
@{
    ViewBag.CurrentMenu = "Department";
    Layout = "_Layout";
}
<div class="layui-row">
    <table id="departTable" class="layui-table" lay-filter="departTable" ></table>
</div>
<script type="text/javascript">
    var cols = "";
    layui.use(['table', 'jquery', 'treetable','form'],
        function () {
            var $ = layui.jquery;
            var table = layui.table;
            var treetable = layui.treetable;
            var form = layui.form;

            var loadCols = function () {
                $.ajax({
                    url: '@Url.Action("GetDepartmentTableCols", "department")',
                    type: 'post',
                    dataType: 'json',
                    success: function (res) {
                        if (res.success) {
                            cols = [res.data];
                            loadTables();
                        } else {
                            admin_error(res.msg);
                        }
                    }
                });
            };
            loadCols();
            //渲染表格
            var loadTables = function () {
                //var formData = $("#searchForm").serializeArray();
                //var tempObj = [];
                //for (var i = 0; i < formData.length; i++) {
                //    var temp = { 'field': '', 'conditional': 'Like', 'value': '' };
                //    temp.field = formData[i].name;
                //    temp.value = formData[i].value;
                //    tempObj.push(temp);
                //}
                treetable.render({
                    elem: '#departTable',
                    id: 'departTable',
                    url: "/Department/GetDepartTreeTable?_t=" + new Date().getTime(),
                    page: false, //分页
                    loading: true,
                    treeColIndex: 0,          // 树形图标显示在第几列
                    treeSpid: '00000000-0000-0000-0000-000000000000',// 最上级的父级id
                    treeIdName: 'id',       // id字段的名称
                    treePidName: 'parentId',     // pid字段的名称
                    treeDefaultClose: false,   // 是否默认折叠
                    treeLinkage: true,        // 父级展开时是否自动展开所有子级
                    height: 'full-150',
                    toolbar: '#toolbarButton',
                    cols: cols
                   // ,where: { searchParam: JSON.stringify(tempObj) }
                });
            };

            //监听工具条
            table.on('tool(departTable)', function (obj) {
                var data = obj.data; //获得当前行数据
                switch (obj.event) {
                    case 'addDepart':
                        top.layer.open({
                            title: '新增',
                            area: ["600px", "500px"],
                            type: 2,
                            maxmin: true,
                            content: '@Url.Action("EditPage", "Department")?pid=' + data.id,
                            end: function () {
                                loadTables();
                            }
                        });
                        break;
                    case 'editDepart':
                        if (data === undefined||data.id==='') {
                            admin_warning("请选择一行数据");
                            return false;
                        }
                        top.layer.open({
                            title: '编辑',
                            area: ["600px", "500px"],
                            type: 2,
                            maxmin: true,
                            content: '@Url.Action("EditPage", "Department")?id=' + data.id,
                            end: function () {
                                loadTables();
                            }
                        });
                        break;
                    case 'delDepart':
                         top.layer.confirm("将同时删除下级部门,确认删除?",
                            {
                                btn: ["确定", "取消"]
                            },
                            function () {
                                var sendData = { "id": data.id };
                                $.ajax({
                                    url: '@Url.Action("Delete", "Department")',
                                    type: 'post',
                                    data: sendData,
                                    dataType: 'json',
                                    success: function (res) {
                                        if (res.success) {
                                            top.layer.msg(res.msg, { icon: 1, offset: '15px' });
                                            loadTables();
                                        } else {
                                            top.layer.msg(res.msg, { icon: 2, offset: '15px' });
                                        }
                                    }
                                });
                            });
                        break;
                };
            });
            //监听事件
            table.on('toolbar(departTable)', function (obj) {
                var pid = '00000000-0000-0000-0000-000000000000';
                switch (obj.event) {
                    case 'addTopDepart':
                       top.layer.open({
                            title: '新增',
                            area: ["600px", "500px"],
                            type: 2,
                            maxmin: true,
                            content: '@Url.Action("EditPage", "Department")?pid=' + pid,
                            end: function () {
                                loadTables();
                            }
                        });
                        break;
                }
            });

            //查询提交
            form.on('submit(btnSubmit)', function (data) {
                loadTables();
                return false;
            });
            //查询提交
            form.on('submit(btnReset)', function (data) {
                loadTables();
                return false;
            });
        });
</script>